---
- hosts: all
  vars_files:
   - pass.yml
  tasks:
  - name: Update root password
    become: no
    user:
      name: root
      update_password: always
      password: "{{ root_pw | password_hash('sha512') }}"
